---
# tasks file for pg_install

- name: Установить PostgreSQL 14
  ansible.builtin.apt:
    name: postgresql-14
    state: present

- name: Запустить и включить PostgreSQL 14
  ansible.builtin.systemd:
    name: postgresql
    enabled: true
    state: started

- name: Настроить postgresql.conf для сетевого доступа
  ansible.builtin.replace:
    path: /etc/postgresql/14/main/postgresql.conf
    regexp: "^#?\\s*listen_addresses\\s*=\\s*'.*'"
    replace: "listen_addresses = '*'"
  notify: "Postgresql Reloader"

- name: Настроить pg_hba.conf для разрешения подключений
  ansible.builtin.lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    line: "host    all             all             0.0.0.0/0               md5"
    insertafter: EOF
  notify: "Postgresql Reloader"
